### PR TITLE
form的validateFields支持promise用法

### PR DESCRIPTION
**Pull request by mushan0x0**
原来的pr https://github.com/react-component/form/pull/187

### CODE REVIEW

**Comment by mushan0x0** [comment]
@yesmeck

**Comment by yesmeck** [comment]
👍

**Comment by yoyo837** [comment]
@mushan0x0 Only `validateFields` ? Please add this feature for `validateFieldsAndScroll`.

**Comment by mushan0x0** [comment]
@yoyo837 There's a return
https://github.com/react-component/form/blob/bdbd7b03e88b7d76ad58d39d978e5bce0c7abdf8/src/createDOMForm.js#L98

**Comment by yoyo837** [comment]
Wow, I really should read the source code about this.

**Pull request merged**
