### PR TITLE
specify lodash methods to make bundle slimmer

### PR DESCRIPTION
**Pull request by andriijas**

### CODE REVIEW

**Comment by benjycui** [comment]
Nope, just use `lodash/xxx`. Thanks.

**Comment by andriijas** [comment]
@benjycui  the motivation is that other react-components uses it, example: https://github.com/react-component/table/blob/master/package.json#L73

**Comment by benjycui** [comment]
@yesmeck could you replace all the `lodash.xxx` with `lodash/xxx`? https://github.com/search?l=JSON&p=1&q=org%3Areact-component+lodash&type=Code

`lodash/xxx` will be easier to be maintained

**Comment by yesmeck** [comment]
Done.

**Pull request closed without merging**
